// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Kg0KAyOU8ZT0077KvIsNkXPNKkOpPX4',
    appId: '1:266658631850:web:c9f5a8a18644502f5d40d3',
    messagingSenderId: '266658631850',
    projectId: 'optilo-3c61e',
    authDomain: 'optilo-3c61e.firebaseapp.com',
    storageBucket: 'optilo-3c61e.firebasestorage.app',
    measurementId: 'G-TMNE8WV7S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr4o5HExwDjWsjlIMNu-mB8DksYKSfFBU',
    appId: '1:266658631850:android:d7681507506ff9b75d40d3',
    messagingSenderId: '266658631850',
    projectId: 'optilo-3c61e',
    storageBucket: 'optilo-3c61e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP03Yff4y6Kdw0V7FvSyyQtifMHJoRVhg',
    appId: '1:266658631850:ios:b9ed496f3722d3d55d40d3',
    messagingSenderId: '266658631850',
    projectId: 'optilo-3c61e',
    storageBucket: 'optilo-3c61e.firebasestorage.app',
    iosBundleId: 'com.example.lineAll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP03Yff4y6Kdw0V7FvSyyQtifMHJoRVhg',
    appId: '1:266658631850:ios:b9ed496f3722d3d55d40d3',
    messagingSenderId: '266658631850',
    projectId: 'optilo-3c61e',
    storageBucket: 'optilo-3c61e.firebasestorage.app',
    iosBundleId: 'com.example.lineAll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Kg0KAyOU8ZT0077KvIsNkXPNKkOpPX4',
    appId: '1:266658631850:web:509af7730aeef7625d40d3',
    messagingSenderId: '266658631850',
    projectId: 'optilo-3c61e',
    authDomain: 'optilo-3c61e.firebaseapp.com',
    storageBucket: 'optilo-3c61e.firebasestorage.app',
    measurementId: 'G-P4YH58J0NH',
  );

}