default_platform(:android)

platform :android do
  desc "Build + upload to internal track for testing"
  lane :test do
    # 1) 빌드 (fvm 사용 시)
    sh "fvm flutter clean"
    sh "fvm flutter pub get"
    sh "fvm flutter build appbundle --release"
    
    # 2) 업로드 (production 트랙)
    upload_to_play_store(
      	aab: "../build/app/outputs/bundle/release/app-release.aab",
        track: "internal"
    )
  end


  desc "Build + upload to production track"
  lane :production do |options|

    # 1) 빌드 (fvm 사용 시)
    sh "fvm flutter clean"
    sh "fvm flutter pub get"
    sh "fvm flutter build appbundle --release"

    # 2) 업로드 (production 트랙)
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "production",
      # release_status: "completed" # 또는 'draft' 등``
    )
  end
end